- apt:
    update-cache: false
    name: caddy
    state: present

- group:
    name: caddyuser
    state: present

- group:
    name: web
    state: present

- user:
    name: "caddyuser"
    state: present
    group: caddyuser
    groups: web
    append: yes

- file:
    path: /home/caddyuser
    state: directory
    owner: caddyuser
    group: web
    mode: '0775'

- file:
    path: /home/caddyuser/publicsite
    state: directory
    owner: caddyuser
    group: web
    mode: '2775'

- copy:
    src: "Caddyfile"
    dest: /etc/caddy/Caddyfile
    owner: root
    mode: '0644'
  notify: "restart caddy"

- copy:
    dest: /home/caddyuser/publicsite/index.html
    src: "index.html"
    owner: caddyuser
    group: web
    mode: '0664'
    force: false
  notify: "restart caddy"

- service:
    name: caddy
    state: started
    enabled: true
