- apt:
    name: ufw
    state: present

- service:
    name: ufw
    enabled: true

- ufw:
    policy: deny
    state: enabled
    logging: on

- ufw:
    rule: allow
    port: '22,80,443,8080'
    proto: tcp

- apt:
    name: fail2ban
    state: present

- service:
    name: fail2ban
    state: started
    enabled: yes
