- apt:
    update_cache: yes
    cache_valid_time: 3600

- apt:
    name:
      - git
      - ufw
      - nano
      - htop
      - curl
      - build-essential
      - python3
      - nodejs
      - openssh-client
      - fail2ban
    state: present
